// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatsApp;

#nullable disable

namespace WatsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518165955_AgregarTablaCloudinaryResources")]
    partial class AgregarTablaCloudinaryResources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("WatsApp.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WatsApp.Models.CloudinaryResource", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Hash");

                    b.ToTable("CloudinaryResources");
                });

            modelBuilder.Entity("WatsApp.Models.UserData", b =>
                {
                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("photoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
